import { CalendarDays, Check, CircleX, Edit3 } from 'lucide-react'

export default function AttendanceHistoryTable({ records, loading, error, emptyMessage = 'No attendance records found.', editable = false, onEdit }) {
  if (loading) return <div className="students-state"><div className="loading-spinner" /><p>Loading attendance history...</p></div>
  if (error) return <div className="students-state"><div className="student-dashboard-error"><CircleX size={19} /></div><h2>Could not load history</h2><p>{error}</p></div>
  if (records.length === 0) return <div className="students-state"><CalendarDays size={24} /><h2>No attendance records</h2><p>{emptyMessage}</p></div>

  return <div className="students-table-wrap"><table><thead><tr><th>Date</th><th>Student</th><th>Subject</th><th>Section</th><th>Faculty</th><th>Status</th>{editable && <th>Action</th>}</tr></thead><tbody>{records.map((record) => { const studentUser = record.student?.userId || {}; const facultyUser = record.faculty?.userId || {}; return <tr key={record._id}><td>{new Date(record.date).toLocaleDateString()}</td><td><div className="student-identity"><span className="student-avatar">{(studentUser.name || record.student?.rollNumber || 'ST').slice(0, 2).toUpperCase()}</span><div><strong>{studentUser.name || record.student?.rollNumber || 'Student'}</strong><small>{record.student?.rollNumber || 'No roll number'}</small></div></div></td><td><span className="roll-number">{record.subject?.code || 'Subject'}</span><small className="table-subtext">{record.subject?.name || ''}</small></td><td>{record.section?.name || 'Section'}</td><td>{facultyUser.name || record.faculty?.employeeId || 'Faculty'}</td><td><span className={`history-status ${record.status}`}><span>{record.status === 'present' ? <Check size={12} /> : <CircleX size={12} />}</span>{record.status}</span></td>{editable && <td><button className="history-edit-button" type="button" onClick={() => onEdit(record)} aria-label="Correct attendance"><Edit3 size={14} /></button></td>}</tr> })}</tbody></table></div>
}
